apiVersion: v1
kind: Service
metadata:
  name: {{ include "maxscale.fullname" . }}
  labels:
    {{- include "maxscale.labels" . | nindent 4 }}
spec:
  ports:
    - name: mariadb
      port: {{ .Values.service.mariadbport }}
    - name: maxscale
      port: {{ .Values.service.restapiport }}
  selector:
    {{- include "maxscale.selectorLabels" . | nindent 4 }}
